from django.contrib import admin
from django.urls import path, include
from OsasSystem import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('OsasSystem.urls')),
    path('home/', views.home, name="home"),
#---------------------------------------------LOGIN------------------------------------------------------------------------------------------------
    path('login/', views.login, name="login"),
    path('login/', views.logout, name="logout"),
    path('activate_account/', views.activate_account, name="activate_account"),
    # path('account_process/', views.account_process, name="account_process"),
    path('register_organization/', views.register_organization, name="register_organization"),
#-----------------------------------------REGISTRATION---------------------------------------------------------------------------------------------
 
#---------------------------------------STUDENT PROFILE--------------------------------------------------------------------------------------------
    path('student_profile/', views.student_profile, name="student_profile"),
    path('student_profile_view/', views.student_profile_view, name="student_profile_view"),
    path('student_process_add/', views.student_process_add, name="student_process_add"),
    path('add_student/', views.add_student, name="add_student"),
    path('<int:stud_id>/edit_student/', views.edit_student, name="edit_student"),
    path('profile/', views.profile, name="profile"),
    path('organization_student/', views.organization_student, name="organization_student"),
#-------------------------------------------USER ROLE----------------------------------------------------------------------------------------------
    path('userrole/', views.userrole, name="userrole"),
    path('<int:user_id>/edit_user/', views.edit_user, name="edit_user"),
    path('adduserrole/', views.adduserrole, name="adduserrole"),
    path('deactivate_user/', views.deactivate_user, name="deactivate_user"),
    path('deleteuser/', views.deleteuser, name="deleteuser"),

    path('auth_user/', views.auth_user, name="auth_user"),
    path('auth_user_add/', views.auth_user_add, name="auth_user_add"),
    path('auth_edit_user/', views.auth_edit_user, name="auth_edit_user"),
    path('auth_user_update/', views.auth_user_update, name="auth_user_update"),
    path('<int:auth_id>/auth_process_edit/', views.auth_process_edit, name="auth_process_edit"),   
#-----------------------------------------YEAR AND SECTION-----------------------------------------------------------------------------------------
    path('yr_sec/', views.yr_sec, name="yr_sec"),
    path('add_yr_sec/', views.add_yr_sec, name="add_yr_sec"),
    path('edit_yr_sec/', views.edit_yr_sec, name="edit_yr_sec"),
    path('update_yr_sec/', views.update_yr_sec, name="update_yr_sec"),
    path('deactivate_yr_sec/', views.deactivate_yr_sec, name="deactivate_yr_sec"),
#--------------------------------------------COURSE------------------------------------------------------------------------------------------------
    path('course/', views.course, name="course"),  
    path('add_course/', views.add_course, name="add_course"), 
    path('deactivate_course/', views.deactivate_course, name="deactivate_course"), 
    path('edit_course/', views.edit_course, name="edit_course"), 
    path('update_course/', views.update_course, name="update_course"), 
    path('<int:course_id>/course/course_edit', views.course_edit, name="course_edit"),

#---------------------------------------------------------ORGANIZATION---------------------------------------------------------
    path('organization_fund_info/', views.organization_fund_info, name="organization_fund_info"),
    path('organization_changepass/', views.organization_changepass, name="organization_changepass"),
    path('organization_changepass_verify/', views.organization_changepass_verify, name="organization_changepass_verify"),
    path('organization_osas/', views.organization_osas, name="organization_osas"),
    path('organization_student_data/', views.organization_student_data, name="organization_student_data"),
    path('organization_new_account/', views.organization_new_account, name="organization_new_account"),
    path('organization_update_account/', views.organization_update_account, name="organization_update_account"),
    path('organization_status_account/', views.organization_status_account, name="organization_status_account"),

    path('organization_home/', views.organization_home, name="organization_home"),
    path('organization_login/', views.organization_login, name="organization_login"),
    path('organiation_login_process/', views.organiation_login_process, name="organiation_login_process"),
    path('organization_logout/', views.organization_logout, name="organization_logout"),

    path('organization_upload_logo/', views.organization_upload_logo, name="organization_upload_logo"),

    path('osas_accreditation_requirements/', views.osas_accreditation_requirements, name="osas_accreditation_requirements"),
    path('organization_accreditation/', views.organization_accreditation, name="organization_accreditation"),
    path('accreditation/', views.accreditation, name="accreditation"),
    path('organization_addnnote/', views.organization_addnnote, name="organization_addnnote"),
    path('organization_view_messages/', views.organization_view_messages, name="organization_view_messages"),
    path('organization_upload_osas/', views.organization_upload_osas, name="organization_upload_osas"),
    path('organization_view_certificate/', views.organization_view_certificate, name="organization_view_certificate"),
    path('organization_approve/', views.organization_approve, name="organization_approve"),
    path('concept_paper_validate/', views.concept_paper_validate, name="concept_paper_validate"),
    path('organization_dismiss/', views.organization_dismiss, name="organization_dismiss"),
    path('organization_view_document/', views.organization_view_document, name="organization_view_document"),
    path('organization_accreditation_expired/', views.organization_accreditation_expired, name="organization_accreditation_expired"),
    path('organization_expired/', views.organization_expired, name="organization_expired"),
    path('accreditation_document_return/', views.accreditation_document_return, name="accreditation_document_return"),
    path('accreditation_document_delete/', views.accreditation_document_delete, name="accreditation_document_delete"),
    path('organization_generate_report/', views.organization_generate_report, name="organization_generate_report"),
    path('accreditation_osas_msg/', views.accreditation_osas_msg, name="accreditation_osas_msg"),
    path('accreditation_org_msg/', views.accreditation_org_msg, name="accreditation_org_msg"),
    path('organization_osas_msg_seen/', views.organization_osas_msg_seen, name="organization_osas_msg_seen"),
    path('organization_msg_clear/', views.organization_msg_clear, name="organization_msg_clear"),
    path('accreditation_document_sent/', views.accreditation_document_sent, name="accreditation_document_sent"),
    path('accreditation_document_return_osas/', views.accreditation_document_return_osas, name="accreditation_document_return_osas"),

    path('organization_fund/', views.organization_fund, name="organization_fund"),
    path('organization_deposit_fund/', views.organization_deposit_fund, name="organization_deposit_fund"),

    path('classroom_fund/', views.classroom_fund, name="classroom_fund"),
    path('class_request_fund/', views.class_request_fund, name="class_request_fund"),

    path('classroom_changepass/', views.classroom_changepass, name="classroom_changepass"),
    path('classroom_changepass_verify/', views.classroom_changepass_verify, name="classroom_changepass_verify"),

    path('osas_fund/', views.osas_fund, name="osas_fund"),
    path('osas_changepass/', views.osas_changepass, name="osas_changepass"),
    path('osas_changepass_verify/', views.osas_changepass_verify, name="osas_changepass_verify"),
    path('osas_fund_authentication/', views.osas_fund_authentication, name="osas_fund_authentication"),

    path('class_fund_voucher_gen/', views.class_fund_voucher_gen, name="class_fund_voucher_gen"),
    path('class_fund_populate/', views.class_fund_populate, name="class_fund_populate"),
    path('classroom_fund_request_remove/', views.classroom_fund_request_remove, name="classroom_fund_request_remove"),
    path('class_fund_reciept_upload/', views.class_fund_reciept_upload, name="class_fund_reciept_upload"),

    path('classroom_officer/', views.classroom_officer, name="classroom_officer"),
    path('classroom_add_officer/', views.classroom_add_officer, name="classroom_add_officer"),

    path('organization_concept_papers/', views.organization_concept_papers, name="organization_concept_papers"),
    path('conceptpaper_upload/', views.conceptpaper_upload, name="conceptpaper_upload"),
    path('org_concept_paper_send/', views.org_concept_paper_send, name="org_concept_paper_send"),
    path('org_concept_paper_title/', views.org_concept_paper_title, name="org_concept_paper_title"),
    path('concept_document_remove/', views.concept_document_remove, name="concept_document_remove"),
    path('org_concept_paper_document_delete/', views.org_concept_paper_document_delete, name="org_concept_paper_document_delete"),
    path('org_concept_paper_document_return/', views.org_concept_paper_document_return, name="org_concept_paper_document_return"),
    path('org_concept_paper_title/', views.org_concept_paper_title, name="org_concept_paper_title"),
    path('organization_inbox/', views.organization_inbox, name="organization_inbox"),
    path('organization_events/', views.organization_events, name="organization_events"),
    path('org_concept_paper_title/', views.org_concept_paper_title, name="org_concept_paper_title"),
    path('organization_event_populate/', views.organization_event_populate, name="organization_event_populate"),
    path('organization_concept_paper_upload/', views.organization_concept_paper_upload, name="organization_concept_paper_upload"),
    path('organization_accomplishment_upload/', views.organization_accomplishment_upload, name="organization_accomplishment_upload"),
    path('gen_report_get_info_organization/', views.gen_report_get_info_organization, name="gen_report_get_info_organization"),
    path('orgnaization_request_fund/', views.orgnaization_request_fund, name="orgnaization_request_fund"),
    path('organization_fund_reciept_upload/', views.organization_fund_reciept_upload, name="organization_fund_reciept_upload"),
    path('organization_fund_populate/', views.organization_fund_populate, name="organization_fund_populate"),
    path('organization_fund_voucher_gen/', views.organization_fund_voucher_gen, name="organization_fund_voucher_gen"),

    path('organization_officer/', views.organization_officer, name="organization_officer"),
    path('orgnaization_add_officer/', views.orgnaization_add_officer, name="orgnaization_add_officer"),
    path('organization_signature_upload/', views.organization_signature_upload, name="organization_signature_upload"),
    path('officer_remove/', views.officer_remove, name="officer_remove"),

    path('fund_request_remove/', views.fund_request_remove, name="fund_request_remove"),

    path('event_generate_report/', views.event_generate_report, name="event_generate_report"),
    path('event_accomplishment_report/', views.event_accomplishment_report, name="event_accomplishment_report"),

    path('classroom_home/', views.classroom_home, name="classroom_home"),
    path('concept_paper_class_msg/', views.concept_paper_class_msg, name="concept_paper_class_msg"),
    path('class_view_messages/', views.class_view_messages, name="class_view_messages"),
    path('concept_paper_osas_msg/', views.concept_paper_osas_msg, name="concept_paper_osas_msg"),
    path('organization_osas_classroom/', views.organization_osas_classroom, name="organization_osas_classroom"),
    path('organization_osas_new_class_account/', views.organization_osas_new_class_account, name="organization_osas_new_class_account"),
    path('class_concept_papers/', views.class_concept_papers, name="class_concept_papers"),
    path('classroom_conceptpaper_upload/', views.classroom_conceptpaper_upload, name="classroom_conceptpaper_upload"),
    path('classroom_concept_paper_upload/', views.classroom_concept_paper_upload, name="classroom_concept_paper_upload"),
    path('classroom_accomplishment_upload/', views.classroom_accomplishment_upload, name="classroom_accomplishment_upload"),
    path('class_concept_paper_send/', views.class_concept_paper_send, name="class_concept_paper_send"),
    path('class_concept_paper_title/', views.class_concept_paper_title, name="class_concept_paper_title"),
    path('class_concept_paper_document_delete/', views.class_concept_paper_document_delete, name="class_concept_paper_document_delete"),
    path('class_concept_paper_document_return/', views.class_concept_paper_document_return, name="class_concept_paper_document_return"),
    path('classroom_update_account/', views.classroom_update_account, name="classroom_update_account"),
    path('concept_papers/', views.concept_papers, name="concept_papers"),
    path('classroom_event_populate/', views.classroom_event_populate, name="classroom_event_populate"),
    path('classroom_event_change_title/', views.classroom_event_change_title, name="classroom_event_change_title"),
    path('student_events/', views.student_events, name="student_events"),
    path('classroom_event_remove/', views.classroom_event_remove, name="classroom_event_remove"),
    path('classroom_student_data/', views.classroom_student_data, name="classroom_student_data"),
    path('gen_report_get_info_classroom/', views.gen_report_get_info_classroom, name="gen_report_get_info_classroom"),
    
    path('accreditation_upload/', views.accreditation_upload, name="accreditation_upload"),
    path('accreditation_document_remove/', views.accreditation_document_remove, name="accreditation_document_remove"),
    path('accreditation_document_send/', views.accreditation_document_send, name="accreditation_document_send"),
    path('accreditation_sending_files/', views.accreditation_sending_files, name="accreditation_sending_files"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
