# Generated by Django 3.0 on 2020-10-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='osas_r_course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_short', models.CharField(max_length=50, verbose_name='Short Course')),
                ('course_full', models.CharField(max_length=250, verbose_name='Full Course')),
                ('status', models.IntegerField(choices=[(0, 'Disable'), (1, 'Active')], default=1)),
            ],
        ),
    ]
