# Generated by Django 3.0 on 2020-11-01 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='osas_r_course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_short', models.CharField(max_length=50, verbose_name='Short Course')),
                ('course_full', models.CharField(max_length=250, verbose_name='Full Course')),
                ('status', models.BooleanField(default=1)),
                ('sample', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='osas_r_section_and_year',
            fields=[
                ('yas_id', models.AutoField(primary_key=True, serialize=False)),
                ('yas_descriptions', models.CharField(max_length=250, verbose_name='yr and sec desc')),
                ('yas_dateregistered', models.DateTimeField(default=datetime.datetime(2020, 11, 1, 13, 45, 50, 992568, tzinfo=utc))),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='osas_r_stud_registration',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_fname', models.CharField(max_length=20)),
                ('s_lname', models.CharField(max_length=20)),
                ('s_no', models.CharField(max_length=15)),
                ('s_password', models.CharField(max_length=16)),
                ('s_type', models.CharField(default='Student', max_length=10)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 11, 1, 13, 45, 50, 992568, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='osas_r_userrole',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('user_username', models.CharField(max_length=50, verbose_name='User Name')),
                ('user_password', models.CharField(max_length=16, verbose_name='User Password')),
                ('user_email', models.EmailField(max_length=50, verbose_name='User Email')),
                ('user_type', models.CharField(max_length=50, verbose_name='User Type')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 11, 1, 13, 45, 50, 992568, tzinfo=utc))),
            ],
        ),
    ]
