# Generated by Django 3.0 on 2021-03-06 05:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osas_notif',
            name='notif_complaint_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_t_complaint'),
        ),
        migrations.AlterField(
            model_name='osas_notif',
            name='notif_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_notif',
            name='notif_excuse_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_t_excuse'),
        ),
        migrations.AlterField(
            model_name='osas_notif',
            name='notif_lost_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_t_id'),
        ),
        migrations.AlterField(
            model_name='osas_notif',
            name='notif_sanction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_t_sanction'),
        ),
        migrations.AlterField(
            model_name='osas_r_auth_user',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_code_title',
            name='ct_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_add_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc), max_length=50),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_designation_office',
            name='designation_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_disciplinary_sanction',
            name='ds_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_complaint',
            name='comp_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_excuse',
            name='excuse_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_excuse',
            name='excuse_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_sanction',
            name='sanction_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 3, 6, 5, 39, 18, 368361, tzinfo=utc)),
        ),
    ]
