# Generated by Django 3.0 on 2020-11-08 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osas_r_stud_registration',
            old_name='student_id',
            new_name='reg_id',
        ),
        migrations.AddField(
            model_name='osas_r_stud_registration',
            name='stud_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_r_personal_info'),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 17, 36, 57, 484583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 17, 36, 57, 484583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 17, 36, 57, 484583, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_referral',
            name='ref_date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 17, 36, 57, 484583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 17, 36, 57, 484583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_stud_registration',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 17, 36, 57, 484583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 17, 36, 57, 484583, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
