# Generated by Django 3.0 on 2021-05-09 23:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_accreditation',
            name='acc_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='org_accreditation',
            name='acc_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='org_concept_paper',
            name='con_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='org_concept_paper',
            name='con_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization_chat',
            name='msg_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_notif',
            name='notif_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_auth_user',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_code_title',
            name='ct_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_add_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc), max_length=50),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_designation_office',
            name='designation_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_disciplinary_sanction',
            name='ds_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_complaint',
            name='comp_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_excuse',
            name='excuse_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_excuse',
            name='excuse_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_sanction',
            name='sanction_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_year', models.CharField(max_length=50, unique=True)),
                ('room_sec', models.CharField(max_length=50, null=True)),
                ('org_email', models.EmailField(max_length=50)),
                ('org_pass', models.CharField(max_length=16)),
                ('org_status', models.CharField(default='ACTIVE', max_length=10)),
                ('org_submit_date', models.DateField(null=True)),
                ('org_datecreated', models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc))),
                ('org_dateupdated', models.DateField(default=datetime.datetime(2021, 5, 9, 23, 55, 50, 820186, tzinfo=utc))),
                ('org_expiration', models.DateField(null=True)),
                ('org_stud_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_r_personal_info')),
            ],
        ),
        migrations.AddField(
            model_name='org_accreditation',
            name='acc_room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.classroom'),
        ),
    ]
