# Generated by Django 3.0 on 2020-10-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='osas_r_section_and_year',
            fields=[
                ('yas_id', models.IntegerField(primary_key=True, serialize=False)),
                ('yas_descriptions', models.CharField(max_length=250, verbose_name='yr and sec desc')),
                ('yas_dateregistered', models.DateField(max_length=8)),
                ('status', models.IntegerField(choices=[(0, 'Disable'), (1, 'Active')], default=1)),
            ],
        ),
    ]
