# Generated by Django 3.0 on 2021-05-09 23:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0002_auto_20210510_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='org_email',
            new_name='room_email',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='org_submit_date',
            new_name='room_expiration',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='org_pass',
            new_name='room_pass',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='org_status',
            new_name='room_status',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='org_stud_id',
            new_name='room_stud_id',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='org_expiration',
            new_name='room_submit_date',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='org_datecreated',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='org_dateupdated',
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='org_accreditation',
            name='acc_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='org_accreditation',
            name='acc_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='org_concept_paper',
            name='con_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='org_concept_paper',
            name='con_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization_chat',
            name='msg_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_notif',
            name='notif_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_auth_user',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_code_title',
            name='ct_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_add_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc), max_length=50),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_designation_office',
            name='designation_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_disciplinary_sanction',
            name='ds_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_complaint',
            name='comp_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_excuse',
            name='excuse_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_excuse',
            name='excuse_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_sanction',
            name='sanction_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 23, 58, 55, 931709, tzinfo=utc)),
        ),
    ]
