# Generated by Django 3.0 on 2020-11-08 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0002_auto_20201109_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osas_r_stud_registration',
            name='s_no',
        ),
        migrations.AddField(
            model_name='osas_r_stud_registration',
            name='s_username',
            field=models.CharField(default='asdad', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 17, 55, 4, 579001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 17, 55, 4, 579001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 17, 55, 4, 579001, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_referral',
            name='ref_date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 17, 55, 4, 579001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 17, 55, 4, 579001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_stud_registration',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 17, 55, 4, 579001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 17, 55, 4, 579001, tzinfo=utc)),
        ),
    ]
