# Generated by Django 3.0 on 2020-11-06 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0002_auto_20201105_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 6, 0, 1, 56, 649299)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 0, 1, 56, 649299)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 6, 0, 1, 56, 649299), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 0, 1, 56, 649299)),
        ),
        migrations.AlterField(
            model_name='osas_r_stud_registration',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 0, 1, 56, 649299)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 0, 1, 56, 649299)),
        ),
    ]
