# Generated by Django 3.0 on 2020-10-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0002_osas_r_section_and_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='osas_r_personal_info',
            fields=[
                ('stud_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stud_no', models.CharField(max_length=13, unique=True, verbose_name='Student Number')),
                ('stud_lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('stud_fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('stud_mname', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('stud_birthdate', models.DateField(max_length=8)),
                ('stud_gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('stud_address', models.CharField(max_length=50, verbose_name='Student Address')),
                ('stud_email', models.EmailField(max_length=50, verbose_name='Student Email')),
                ('stud_hs', models.CharField(max_length=50, verbose_name='High School')),
                ('stud_hs_add', models.CharField(max_length=50, verbose_name='High School Address')),
                ('date_created', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('stud_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_r_course')),
                ('stud_sec_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_r_section_and_year')),
            ],
        ),
    ]
