# Generated by Django 3.0 on 2020-12-11 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0003_auto_20201123_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAMPLE',
            fields=[
                ('sample', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='osas_r_auth_user',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_competencies',
            name='comp_updateddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_educ',
            name='educ_graduation_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_educ',
            name='educ_updatedteddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_employ',
            name='employ_date1st_employ',
            field=models.DateField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_employ',
            name='employ_date_current',
            field=models.DateField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_employ',
            name='employ_updatedddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_rate',
            name='rate_updatedddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_referral',
            name='ref_date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_relevant',
            name='rel_updatedddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_profile',
            name='prof_updateddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 6, 8, 14, 81075, tzinfo=utc)),
        ),
    ]
