# Generated by Django 3.0 on 2020-11-03 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0003_auto_20201103_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_add_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 11, 59, 11, 642614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 11, 59, 11, 642614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 11, 59, 11, 642614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 11, 59, 11, 642614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_no',
            field=models.CharField(max_length=15, unique=True, verbose_name='Student Number'),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 11, 59, 11, 642614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_stud_registration',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 11, 59, 11, 642614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 11, 59, 11, 642614, tzinfo=utc)),
        ),
    ]
