# Generated by Django 3.0 on 2020-11-09 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0003_auto_20201109_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osas_r_userrole',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='osas_r_userrole',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='osas_r_userrole',
            name='user_password',
        ),
        migrations.RemoveField(
            model_name='osas_r_userrole',
            name='user_status',
        ),
        migrations.RemoveField(
            model_name='osas_r_userrole',
            name='user_username',
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 4, 54, 35, 597679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 4, 54, 35, 597679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 4, 54, 35, 597679, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_referral',
            name='ref_date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 4, 54, 35, 597679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 4, 54, 35, 597679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_stud_registration',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 4, 54, 35, 597679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 4, 54, 35, 597679, tzinfo=utc)),
        ),
    ]
