# Generated by Django 3.0 on 2020-10-24 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0004_osas_r_stud_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='osas_r_emergency_contact',
            fields=[
                ('e_contact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stud_e_name', models.CharField(max_length=50, verbose_name='Emergency Contact Person')),
                ('stud_e_address', models.CharField(max_length=50, verbose_name='Emergency Contact Address')),
                ('e_m_number', models.BigIntegerField(blank='', verbose_name='Mobile Number')),
                ('e_t_number', models.BigIntegerField(blank='', verbose_name='Telephone Number')),
                ('date_created', models.DateField(verbose_name=django.utils.timezone.now)),
                ('date_updated', models.DateField(verbose_name=django.utils.timezone.now)),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_r_personal_info')),
            ],
        ),
    ]
