# Generated by Django 3.0 on 2021-02-10 03:19

import OsasSystem.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0005_auto_20210208_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osas_r_auth_user',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 3, 19, 16, 792398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_code_title',
            name='ct_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 3, 19, 16, 792398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 3, 19, 16, 792398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_designation_office',
            name='designation_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 3, 19, 16, 792398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 3, 19, 16, 792398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 3, 19, 16, 792398, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 3, 19, 16, 792398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 3, 19, 16, 792398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_excuse',
            name='excuse_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 3, 19, 16, 792398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_excuse',
            name='excuse_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 3, 19, 16, 792398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_sanction',
            name='sanction_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 3, 19, 16, 792398, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='osas_t_complaint',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_number', models.CharField(max_length=10)),
                ('comp_letter', models.CharField(max_length=2000)),
                ('comp_pic', models.ImageField(blank=True, null=True, upload_to=OsasSystem.models.image_path)),
                ('comp_status', models.CharField(default='PENDING', max_length=10)),
                ('comp_datecreated', models.DateTimeField(default=datetime.datetime(2021, 2, 10, 3, 19, 16, 792398, tzinfo=utc))),
                ('comp_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_r_personal_info')),
            ],
        ),
    ]
