# Generated by Django 3.0 on 2020-10-24 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0005_osas_r_emergency_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='osas_t_id',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateField(verbose_name=django.utils.timezone.now)),
                ('date_updated', models.DateField(verbose_name=django.utils.timezone.now)),
                ('lost_id_status', models.IntegerField(choices=[(1, 'Approved'), (0, 'Pending')], default=0)),
                ('lost_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_r_personal_info')),
            ],
        ),
    ]
