# Generated by Django 3.0 on 2020-11-09 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0005_auto_20201109_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 12, 38, 28, 137502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 12, 38, 28, 137502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 12, 38, 28, 137502, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_referral',
            name='ref_date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 12, 38, 28, 137502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 12, 38, 28, 137502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 12, 38, 28, 137502, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='osas_r_auth_user',
            fields=[
                ('auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_lname', models.CharField(max_length=50)),
                ('auth_fname', models.CharField(max_length=50)),
                ('auth_username', models.CharField(max_length=50)),
                ('auth_password', models.CharField(max_length=16)),
                ('date_created', models.DateTimeField(blank=True, max_length=50)),
                ('date_updated', models.DateTimeField(default=datetime.datetime(2020, 11, 9, 12, 38, 28, 137502, tzinfo=utc))),
                ('auth_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_r_userrole')),
            ],
        ),
    ]
