# Generated by Django 3.0 on 2020-11-06 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0005_auto_20201106_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='osas_r_referral',
            fields=[
                ('ref_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_name', models.CharField(max_length=250, null=True)),
                ('ref_email', models.EmailField(blank=True, max_length=50)),
                ('ref_contact', models.BigIntegerField(max_length=11, null=True)),
                ('ref_share', models.CharField(max_length=250, null=True)),
                ('ref_date_created', models.DateTimeField(max_length=50)),
                ('ref_date_updated', models.DateTimeField(default=datetime.datetime(2020, 11, 6, 17, 22, 39, 292554, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 6, 17, 22, 39, 292554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 17, 22, 39, 292554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2020, 11, 6, 17, 22, 39, 292554, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 17, 22, 39, 292554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_stud_registration',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 17, 22, 39, 292554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 17, 22, 39, 292554, tzinfo=utc)),
        ),
    ]
