# Generated by Django 3.0 on 2020-11-03 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0005_auto_20201103_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_add_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 15, 36, 14, 734367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 15, 36, 14, 734367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 15, 36, 14, 734367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 15, 36, 14, 734367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 15, 36, 14, 734367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_stud_registration',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 15, 36, 14, 734367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 15, 36, 14, 734367, tzinfo=utc)),
        ),
    ]
