# Generated by Django 3.0 on 2020-10-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0006_osas_t_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='osas_t_admission',
            fields=[
                ('admission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('request_name', models.CharField(max_length=50, verbose_name='Name of Request')),
                ('request_detail', models.CharField(max_length=50, verbose_name='Request Details')),
                ('admission_status', models.CharField(max_length=50, verbose_name='Admission Status')),
                ('admission_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OsasSystem.osas_r_personal_info')),
            ],
        ),
    ]
