# Generated by Django 3.0 on 2020-10-25 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0007_osas_t_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_created',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
