# Generated by Django 3.0 on 2020-10-25 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0009_auto_20201025_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='osas_r_stud_registration',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_fname', models.CharField(max_length=20)),
                ('s_lname', models.CharField(max_length=20)),
                ('s_no', models.CharField(max_length=13)),
                ('s_password', models.CharField(max_length=16)),
                ('date_created', models.DateField(verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='osas_r_userrole',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('user_username', models.CharField(max_length=50, verbose_name='User Name')),
                ('user_password', models.CharField(max_length=16, verbose_name='User Password')),
                ('user_email', models.EmailField(max_length=50, verbose_name='User Email')),
                ('user_type', models.IntegerField(choices=[(1, 'Student'), (2, 'Admin'), (3, 'Head')], max_length=50, verbose_name='User Type')),
            ],
        ),
        migrations.AlterField(
            model_name='osas_r_emergency_contact',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 10, 25, 14, 18, 58, 410549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_emergency_contact',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2020, 10, 25, 14, 18, 58, 410549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 10, 25, 14, 18, 58, 410549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2020, 10, 25, 14, 18, 58, 410549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_stud_contact',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 10, 25, 14, 18, 58, 410549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_stud_contact',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2020, 10, 25, 14, 18, 58, 410549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_id',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 10, 25, 14, 18, 58, 410549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_id',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2020, 10, 25, 14, 18, 58, 410549, tzinfo=utc)),
        ),
    ]
