# Generated by Django 3.0 on 2021-03-01 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0010_auto_20210211_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='osas_t_complaint',
            name='comp_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='osas_t_complaint',
            name='comp_g_assign',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='osas_t_complaint',
            name='comp_nature',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='osas_r_auth_user',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 16, 6, 7, 362437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_code_title',
            name='ct_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 16, 6, 7, 362437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 16, 6, 7, 362437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_designation_office',
            name='designation_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 16, 6, 7, 362437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 16, 6, 7, 362437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 16, 6, 7, 362437, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 16, 6, 7, 362437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 16, 6, 7, 362437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_complaint',
            name='comp_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 16, 6, 7, 362437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_complaint',
            name='comp_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='osas_t_excuse',
            name='excuse_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 16, 6, 7, 362437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_excuse',
            name='excuse_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 16, 6, 7, 362437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_sanction',
            name='sanction_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 16, 6, 7, 362437, tzinfo=utc)),
        ),
    ]
