# Generated by Django 3.0 on 2020-10-27 15:42

import OsasSystem.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0013_auto_20201027_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='osas_r_userrole',
            name='s_image',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=OsasSystem.models.image_path),
        ),
        migrations.AlterField(
            model_name='osas_r_emergency_contact',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 15, 42, 28, 272029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_emergency_contact',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 15, 42, 28, 272029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 15, 42, 28, 272029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 15, 42, 28, 272029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_stud_contact',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 15, 42, 28, 272029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_stud_contact',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 15, 42, 28, 272029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_id',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 15, 42, 28, 272029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_t_id',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 15, 42, 28, 272029, tzinfo=utc)),
        ),
    ]
