# Generated by Django 3.0 on 2021-08-03 04:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OsasSystem', '0059_auto_20210801_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osas_r_disciplinary_sanction',
            name='ds_code_id',
        ),
        migrations.RemoveField(
            model_name='osas_t_complaint',
            name='comp_stud_id',
        ),
        migrations.RemoveField(
            model_name='osas_t_excuse',
            name='excuse_stud_id',
        ),
        migrations.RemoveField(
            model_name='osas_t_id',
            name='lost_stud_id',
        ),
        migrations.RemoveField(
            model_name='osas_t_id_file',
            name='id_lost_id',
        ),
        migrations.RemoveField(
            model_name='osas_t_sanction',
            name='sanction_auth_id',
        ),
        migrations.RemoveField(
            model_name='osas_t_sanction',
            name='sanction_code_id',
        ),
        migrations.RemoveField(
            model_name='osas_t_sanction',
            name='sanction_designation_id',
        ),
        migrations.RemoveField(
            model_name='osas_t_sanction',
            name='sanction_excuse_id',
        ),
        migrations.RemoveField(
            model_name='osas_t_sanction',
            name='sanction_stud_id',
        ),
        migrations.RemoveField(
            model_name='osas_t_sanction',
            name='sanction_t_id',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='concept_paper_title',
            name='title_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_date_requested',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='officer',
            name='off_date_added',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='org_accreditation',
            name='acc_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='org_accreditation',
            name='acc_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='org_concept_paper',
            name='con_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='org_concept_paper',
            name='con_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_datecreated',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_dateupdated',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organization_chat',
            name='msg_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_auth_user',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_add_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc), max_length=50),
        ),
        migrations.AlterField(
            model_name='osas_r_course',
            name='course_edit_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_personal_info',
            name='stud_birthdate',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc), max_length=12),
        ),
        migrations.AlterField(
            model_name='osas_r_section_and_year',
            name='yas_dateregistered',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='osas_r_userrole',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 4, 14, 13, 775493, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='osas_notif',
        ),
        migrations.DeleteModel(
            name='osas_r_code_title',
        ),
        migrations.DeleteModel(
            name='osas_r_designation_office',
        ),
        migrations.DeleteModel(
            name='osas_r_disciplinary_sanction',
        ),
        migrations.DeleteModel(
            name='osas_t_complaint',
        ),
        migrations.DeleteModel(
            name='osas_t_excuse',
        ),
        migrations.DeleteModel(
            name='osas_t_id',
        ),
        migrations.DeleteModel(
            name='osas_t_id_file',
        ),
        migrations.DeleteModel(
            name='osas_t_sanction',
        ),
    ]
